# run: conda env create --file environment.yml
name: wowed_volcano
channels:
  - conda-forge
dependencies:

# general dependencies
- python>3.10
- pip>19.0
- tqdm
- jupyter
- jupyterlab
- ipykernel

# array processing
- numpy
- pandas
- xarray

# plotting
- matplotlib

# general scientific libraries
- scipy
- scikit-learn
- scikit-image
- pygad

# parallel processing
- mpire

- pip:
  - utm
  - ipympl
  - bqplot
  - ipywidgets
  - ipyleaflet
  - pykonal
  