# run: conda env create --file environment.yml
name: wowved_24_06
channels:
  - pytorch
  - conda-forge
dependencies:

# general dependencies
- python>3.10
- pip>19.0
- tqdm

# array processing
- numpy
- pandas
- xarray

# ML libraries 
- pytorch

# plotting
- matplotlib

# parallel processing
# - dill
# - mpire
# - joblib

# general scientific libraries
- scipy
- shapely
- scikit-learn
- scikit-image

- pip:
  - zuko
  - utm
  - ipympl
  - bqplot